name: Update Packages 

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 */7 * *"

permissions: read-all

jobs:
  get-packages:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    permissions:
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0
        clean: true

    - name: Get New Packages
      run: |
        echo "Fetch new Versions"
        if test -f "./.templates/ci/update-packages.sh"; then
           bash "./.templates/ci/update-packages.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}

